### ISSUE TITLE
[bug]raise NewConnectionError 导致异常退出

### ISSUE THREAD

**Issue by Xm798** [yaomeng0722/genshin_task-resin-expedition_alert#23]
发现 docker 总是会因为异常退出，今天给文档加上了 `restart=always`，但是没有解决根本的问题啊…
面向百度的编程也没有得出结果，难道是我网络不稳定……？
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f5636b0dd00>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api-takumi.mihoyo.com', port=443): Max retries exceeded with url: /game_record/app/genshin/api/dailyNote?server=cn_gf01&role_id=178555946 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5636b0dd00>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/./index.py", line 3, in <module>
    main()
  File "/app/alert/__init__.py", line 83, in main
    alert= check(uid, cookie, name)
  File "/app/alert/__init__.py", line 23, in check
    base_data: BaseData = MysAPI(uid, cookie).get_dailyNote()
  File "/app/alert/getinfo/__init__.py", line 52, in get_dailyNote
    return BaseData.parse_obj(self._request(url, params=self.body, cookie=self.cookie))
  File "/app/alert/getinfo/__init__.py", line 39, in _request
    response = session.request(method, url, headers=headers.new(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-takumi.mihoyo.com', port=443): Max retries exceeded with url: /game_record/app/genshin/api/dailyNote?server=cn_gf01&role_id=178555946 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5636b0dd00>: Failed to establish a new connection: [Errno -3] Try again'))
```

**Comment by yaomeng0722** [comment]
不懂docker...

**Comment by yaomeng0722** [comment]
> 发现 docker 总是会因为异常退出，今天给文档加上了 `restart=always`，但是没有解决根本的问题啊… 面向百度的编程也没有得出结果，难道是我网络不稳定……？
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
>     conn = connection.create_connection(
>   File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
>     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
>   File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno -3] Try again
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
>     httplib_response = self._make_request(
>   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
>     self._validate_conn(conn)
>   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
>     conn.connect()
>   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
>     conn = self._new_conn()
>   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
>     raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f5636b0dd00>: Failed to establish a new connection: [Errno -3] Try again
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
>     resp = conn.urlopen(
>   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
>     retries = retries.increment(
>   File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api-takumi.mihoyo.com', port=443): Max retries exceeded with url: /game_record/app/genshin/api/dailyNote?server=cn_gf01&role_id=178555946 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5636b0dd00>: Failed to establish a new connection: [Errno -3] Try again'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/app/./index.py", line 3, in <module>
>     main()
>   File "/app/alert/__init__.py", line 83, in main
>     alert= check(uid, cookie, name)
>   File "/app/alert/__init__.py", line 23, in check
>     base_data: BaseData = MysAPI(uid, cookie).get_dailyNote()
>   File "/app/alert/getinfo/__init__.py", line 52, in get_dailyNote
>     return BaseData.parse_obj(self._request(url, params=self.body, cookie=self.cookie))
>   File "/app/alert/getinfo/__init__.py", line 39, in _request
>     response = session.request(method, url, headers=headers.new(
>   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-takumi.mihoyo.com', port=443): Max retries exceeded with url: /game_record/app/genshin/api/dailyNote?server=cn_gf01&role_id=178555946 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5636b0dd00>: Failed to establish a new connection: [Errno -3] Try again'))
> ```

盲猜与最下面一行有关，
```requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-takumi.mihoyo.com', port=443): Max retries exceeded with url: /game_record/app/genshin/api/dailyNote?server=cn_gf01&role_id=178555946 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5636b0dd00>: Failed to establish a new connection: [Errno -3] Try again'))``` 
而不是docker的问题

**Comment by Xm798** [comment]
> > 发现 docker 总是会因为异常退出，今天给文档加上了 `restart=always`，但是没有解决根本的问题啊… 面向百度的编程也没有得出结果，难道是我网络不稳定……？
> > 
> > ```
> > Traceback (most recent call last):
> >   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
> >     conn = connection.create_connection(
> >   File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
> >     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
> >   File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
> >     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> > socket.gaierror: [Errno -3] Try again
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
> >     httplib_response = self._make_request(
> >   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
> >     self._validate_conn(conn)
> >   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
> >     conn.connect()
> >   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
> >     conn = self._new_conn()
> >   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
> >     raise NewConnectionError(
> > urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f5636b0dd00>: Failed to establish a new connection: [Errno -3] Try again
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
> >     resp = conn.urlopen(
> >   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
> >     retries = retries.increment(
> >   File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
> >     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> > urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api-takumi.mihoyo.com', port=443): Max retries exceeded with url: /game_record/app/genshin/api/dailyNote?server=cn_gf01&role_id=178555946 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5636b0dd00>: Failed to establish a new connection: [Errno -3] Try again'))
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "/app/./index.py", line 3, in <module>
> >     main()
> >   File "/app/alert/__init__.py", line 83, in main
> >     alert= check(uid, cookie, name)
> >   File "/app/alert/__init__.py", line 23, in check
> >     base_data: BaseData = MysAPI(uid, cookie).get_dailyNote()
> >   File "/app/alert/getinfo/__init__.py", line 52, in get_dailyNote
> >     return BaseData.parse_obj(self._request(url, params=self.body, cookie=self.cookie))
> >   File "/app/alert/getinfo/__init__.py", line 39, in _request
> >     response = session.request(method, url, headers=headers.new(
> >   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
> >     resp = self.send(prep, **send_kwargs)
> >   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
> >     r = adapter.send(request, **kwargs)
> >   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
> >     raise ConnectionError(e, request=request)
> > requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-takumi.mihoyo.com', port=443): Max retries exceeded with url: /game_record/app/genshin/api/dailyNote?server=cn_gf01&role_id=178555946 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5636b0dd00>: Failed to establish a new connection: [Errno -3] Try again'))
> > ```
> 
> 盲猜与最下面一行有关，
> ```requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-takumi.mihoyo.com', port=443): Max retries exceeded with url: /game_record/app/genshin/api/dailyNote?server=cn_gf01&role_id=178555946 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5636b0dd00>: Failed to establish a new connection: [Errno -3] Try again'))``` 
> 而不是docker的问题

跟docker没有关系。最后一行难道是因为我自己的网络问题？

**Comment by yaomeng0722** [comment]
> > > 发现 docker 总是会因为异常退出，今天给文档加上了 `restart=always`，但是没有解决根本的问题啊… 面向百度的编程也没有得出结果，难道是我网络不稳定……？
> > > ```
> > > Traceback (most recent call last):
> > >   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
> > >     conn = connection.create_connection(
> > >   File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
> > >     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
> > >   File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
> > >     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> > > socket.gaierror: [Errno -3] Try again
> > > 
> > > During handling of the above exception, another exception occurred:
> > > 
> > > Traceback (most recent call last):
> > >   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
> > >     httplib_response = self._make_request(
> > >   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
> > >     self._validate_conn(conn)
> > >   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
> > >     conn.connect()
> > >   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
> > >     conn = self._new_conn()
> > >   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
> > >     raise NewConnectionError(
> > > urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f5636b0dd00>: Failed to establish a new connection: [Errno -3] Try again
> > > 
> > > During handling of the above exception, another exception occurred:
> > > 
> > > Traceback (most recent call last):
> > >   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
> > >     resp = conn.urlopen(
> > >   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
> > >     retries = retries.increment(
> > >   File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
> > >     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> > > urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api-takumi.mihoyo.com', port=443): Max retries exceeded with url: /game_record/app/genshin/api/dailyNote?server=cn_gf01&role_id=178555946 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5636b0dd00>: Failed to establish a new connection: [Errno -3] Try again'))
> > > 
> > > During handling of the above exception, another exception occurred:
> > > 
> > > Traceback (most recent call last):
> > >   File "/app/./index.py", line 3, in <module>
> > >     main()
> > >   File "/app/alert/__init__.py", line 83, in main
> > >     alert= check(uid, cookie, name)
> > >   File "/app/alert/__init__.py", line 23, in check
> > >     base_data: BaseData = MysAPI(uid, cookie).get_dailyNote()
> > >   File "/app/alert/getinfo/__init__.py", line 52, in get_dailyNote
> > >     return BaseData.parse_obj(self._request(url, params=self.body, cookie=self.cookie))
> > >   File "/app/alert/getinfo/__init__.py", line 39, in _request
> > >     response = session.request(method, url, headers=headers.new(
> > >   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
> > >     resp = self.send(prep, **send_kwargs)
> > >   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
> > >     r = adapter.send(request, **kwargs)
> > >   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
> > >     raise ConnectionError(e, request=request)
> > > requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-takumi.mihoyo.com', port=443): Max retries exceeded with url: /game_record/app/genshin/api/dailyNote?server=cn_gf01&role_id=178555946 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5636b0dd00>: Failed to establish a new connection: [Errno -3] Try again'))
> > > ```
> > 
> > 
> > 盲猜与最下面一行有关，
> > `requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-takumi.mihoyo.com', port=443): Max retries exceeded with url: /game_record/app/genshin/api/dailyNote?server=cn_gf01&role_id=178555946 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5636b0dd00>: Failed to establish a new connection: [Errno -3] Try again'))`
> > 而不是docker的问题
> 
> 跟docker没有关系。最后一行难道是因为我自己的网络问题？

当 load 到不同主机后，由于镜像的配置文件完整保存，默认的 bridge 网络会继承原主机的配置项，这样会导致在另一个主机上可能会出现网络请求无法发出的问题，这时可以通过直接将 bridge 网络转换为 host 网络就可以解决错误

百度出来的

**Comment by Xm798** [comment]
> > > > 发现 docker 总是会因为异常退出，今天给文档加上了 `restart=always`，但是没有解决根本的问题啊… 面向百度的编程也没有得出结果，难道是我网络不稳定……？
> > > > ```
> > > > Traceback (most recent call last):
> > > >   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
> > > >     conn = connection.create_connection(
> > > >   File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
> > > >     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
> > > >   File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
> > > >     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> > > > socket.gaierror: [Errno -3] Try again
> > > > 
> > > > During handling of the above exception, another exception occurred:
> > > > 
> > > > Traceback (most recent call last):
> > > >   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
> > > >     httplib_response = self._make_request(
> > > >   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
> > > >     self._validate_conn(conn)
> > > >   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
> > > >     conn.connect()
> > > >   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
> > > >     conn = self._new_conn()
> > > >   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
> > > >     raise NewConnectionError(
> > > > urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f5636b0dd00>: Failed to establish a new connection: [Errno -3] Try again
> > > > 
> > > > During handling of the above exception, another exception occurred:
> > > > 
> > > > Traceback (most recent call last):
> > > >   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
> > > >     resp = conn.urlopen(
> > > >   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
> > > >     retries = retries.increment(
> > > >   File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
> > > >     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> > > > urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api-takumi.mihoyo.com', port=443): Max retries exceeded with url: /game_record/app/genshin/api/dailyNote?server=cn_gf01&role_id=178555946 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5636b0dd00>: Failed to establish a new connection: [Errno -3] Try again'))
> > > > 
> > > > During handling of the above exception, another exception occurred:
> > > > 
> > > > Traceback (most recent call last):
> > > >   File "/app/./index.py", line 3, in <module>
> > > >     main()
> > > >   File "/app/alert/__init__.py", line 83, in main
> > > >     alert= check(uid, cookie, name)
> > > >   File "/app/alert/__init__.py", line 23, in check
> > > >     base_data: BaseData = MysAPI(uid, cookie).get_dailyNote()
> > > >   File "/app/alert/getinfo/__init__.py", line 52, in get_dailyNote
> > > >     return BaseData.parse_obj(self._request(url, params=self.body, cookie=self.cookie))
> > > >   File "/app/alert/getinfo/__init__.py", line 39, in _request
> > > >     response = session.request(method, url, headers=headers.new(
> > > >   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
> > > >     resp = self.send(prep, **send_kwargs)
> > > >   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
> > > >     r = adapter.send(request, **kwargs)
> > > >   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
> > > >     raise ConnectionError(e, request=request)
> > > > requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-takumi.mihoyo.com', port=443): Max retries exceeded with url: /game_record/app/genshin/api/dailyNote?server=cn_gf01&role_id=178555946 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5636b0dd00>: Failed to establish a new connection: [Errno -3] Try again'))
> > > > ```
> > > 
> > > 
> > > 盲猜与最下面一行有关，
> > > `requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-takumi.mihoyo.com', port=443): Max retries exceeded with url: /game_record/app/genshin/api/dailyNote?server=cn_gf01&role_id=178555946 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5636b0dd00>: Failed to establish a new connection: [Errno -3] Try again'))`
> > > 而不是docker的问题
> > 
> > 
> > 跟docker没有关系。最后一行难道是因为我自己的网络问题？
> 
> 当 load 到不同主机后，由于镜像的配置文件完整保存，默认的 bridge 网络会继承原主机的配置项，这样会导致在另一个主机上可能会出现网络请求无法发出的问题，这时可以通过直接将 bridge 网络转换为 host 网络就可以解决错误
> 
> 百度出来的

应该不是这个问题，一直都是在一台服务器上跑的。如果其他人没遇到的话，就当是我网络问题吧（
