### ISSUE TITLE
老哥我这咋一直报“发生错误，请检查cookie与id是否对应或是否已开启米游社实时便笺功能”这个错误

### ISSUE THREAD

**Issue by 1053960054** [yaomeng0722/genshin_task-resin-expedition_alert#30]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/./index.py", line 3, in <module>
    main()
  File "/app/alert/__init__.py", line 126, in main
    alert = check(uid, cookie)
  File "/app/alert/__init__.py", line 26, in check
    send(status="error", message="发生错误，请检查cookie与id是否对应或是否已开启米游社实时便笺功能。")
TypeError: send() missing 1 required positional argument: 'text'
Traceback (most recent call last):
  File "/app/alert/__init__.py", line 24, in check
    base_data: BaseData = MysAPI(uid, cookie).get_dailyNote()
  File "/app/alert/getinfo/__init__.py", line 52, in get_dailyNote
    return BaseData.parse_obj(self._request(url, params=self.body, cookie=self.cookie))
  File "/app/alert/getinfo/__init__.py", line 47, in _request
    raise APIError(response.retcode, response.message)
alert.getinfo.exceptions.APIError: -1: Params error

我已经核对过cookie和游戏id了，相同的cookie跑自动签到没问题，这边就报错

**Comment by yaomeng0722** [comment]
我明天看看嗷

**Comment by Xm798** [comment]
实时便笺开了吗？第一次用要去米游社先打开实时便笺

**Comment by 1053960054** [comment]
> 第一次用去米游社先打开便笺打开了？

权限也开了

**Comment by yaomeng0722** [comment]
> > 第一次用去米游社先打开便笺打开了？
> 
> 权限也开了

他修复了，原因是少了一个参数，现在我测试的已经没问题了~不妨再试一试

**Comment by Xm798** [comment]
> > > 第一次用去米游社先打开便笺打开了？
> > 
> > 
> > 权限也开了
> 
> 他修复了，原因是少了一个参数，现在我测试的已经没问题了~不妨再试一试

但是我觉得不是这个问题，这个参数的问题只有发生错误的时候才会被触发，如果如果一切正常的话不会执行`send(status="error", message="发生错误，请检查cookie与id是否对应或是否已开启米游社实时便笺功能。")`，这个bug只是会造成程序异常退出而已。。所以我也一直没发现这个问题。。

**Comment by 1053960054** [comment]
> > > 第一次用去米游社先打开便笺打开了？
> > 
> > 
> > 权限也开了
> 
> 他修复了，原因是少了一个参数，现在我测试的已经没问题了~不妨再试一试

我重新拉了下

> > > 第一次用去米游社先打开便笺打开了？
> > 
> > 
> > 权限也看看
> 
> 他修复了，原因是少了一个参数，现在我测试的已经没问题了~下次再试一试



> > > 第一次用去米游社先打开便笺打开了？
> > 
> > 
> > 权限也看看
> 
> 他修复了，原因是少了一个参数，现在我测试的已经没问题了~下次再试一试

还是一样的报错

**Comment by yaomeng0722** [comment]
啊。。你有python基础吗

**Comment by 1053960054** [comment]
> 啊。。你有python基础吗



> 啊。。你有python基础吗，或者说有开发环境吗



> 啊。。你有python基础吗，或者说有开发环境吗

我更新到了python3.9，然后试了下docker 和git clone到本地都是报相同的错误，本地的话pushplus有推送和上面一样的错误信息。

**Comment by Xm798** [comment]
> 

我觉得不是项目的问题，应该还是cookie的问题。。我这边三个账号都没问题，建议重新抓一下cookie试一下？或者配置文件格式有没有错误

**Comment by yaomeng0722** [comment]
genshin_task-resin-expedition_alert/alert/getinfo/__init__.py 
在这个文件的39行打个断点看response完整内容是个啥

**Comment by 1053960054** [comment]
> genshin_task-resin-expedition_alert/alert/getinfo/**init**.py 在这个文件的39行打个断点看response完整内容是个啥

我试下看看，没学过python

**Comment by Xm798** [comment]
我觉得还是cookie的原因，我这边三个账号本地和docker都是正常的。建议在确认米游社实时便签正常显示的情况下，重新抓一下cookie试试，然后确认一下配置文件格式有没有问题

**Comment by yaomeng0722** [comment]
> > genshin_task-resin-expedition_alert/alert/getinfo/**init**.py 在这个文件的39行打个断点看response完整内容是个啥
> 
> 我试下看看，没学过python

毕竟我不方便和你要cookie。。只能这样麻烦你了，也只是看一个变量存储的信息而已

**Comment by 1053960054** [comment]
> > > genshin_task-resin-expedition_alert/alert/getinfo/**init**.py 在这个文件的39行打个断点看response完整内容是个啥
> > 
> > 
> > 我试下看看，没学过python
> 
> 毕竟我不方便和你要cookie。。只能这样麻烦你了，也只是看一个变量存储的信息而已

我打了断点看了下，response这里获取到了我的cookie和角色id

**Comment by Xm798** [comment]
> > > > genshin_task-resin-expedition_alert/alert/getinfo/**init**.py 在这个文件的39行打个断点看response完整内容是个啥
> > > 
> > > 
> > > 我试下看看，没学过python
> > 
> > 
> > 毕竟我不方便和你要cookie。。只能这样麻烦你了，也只是看一个变量存储的信息而已
> 
> 我打了断点看了下，response这里获取到了我的cookie和角色id

![image](https://user-images.githubusercontent.com/48074861/143243503-5eb464ed-a712-428a-8e56-6375230bf7cd.png)
`response`能够正常返回数据吗？`retcode`应该是0

**Comment by 1053960054** [comment]
> 
没有，我在下面加了一行 "print(response)"
都没打印到控制台，不知道这个和java一不一样，我想debug的时候看下里面的值，结果都没有

**Comment by yaomeng0722** [comment]
> > 
> 
> 没有，我在下面加了一行 "print(response)" 都没打印到控制台，不知道这个和java一不一样，我想debug的时候看下里面的值，结果都没有

要看的是39行的response，或者在41行之前加 print(response)。
41行的Response.parse_obj是类似数据过滤的东西，估计是不符合要求，所以你打印出来是空值

**Comment by 1053960054** [comment]
![image](https://user-images.githubusercontent.com/38828427/143250396-1617f7ed-69d5-4954-843c-02fa2ba1eb92.png)

**Comment by 1053960054** [comment]
> > > 
> > 
> > 
> > 没有，我在下面加了一行 "print(response)" 都没打印到控制台，不知道这个和java一不一样，我想debug的时候看下里面的值，结果都没有
> 
> 要看的是39行的response，或者在41行之前加 print(response)。 41行的Response.parse_obj是类似数据过滤的东西，估计是不符合要求，所以你打印出来是空值

![image](https://user-images.githubusercontent.com/38828427/143250897-4ae8ecbe-227b-410e-8cd1-ee74896524d3.png)

**Comment by yaomeng0722** [comment]
> > > > 
> > > 
> > > 
> > > 没有，我在下面加了一行 "print(response)" 都没打印到控制台，不知道这个和java一不一样，我想debug的时候看下里面的值，结果都没有
> > 
> > 
> > 要看的是39行的response，或者在41行之前加 print(response)。 41行的Response.parse_obj是类似数据过滤的东西，估计是不符合要求，所以你打印出来是空值
> 
> ![image](https://user-images.githubusercontent.com/38828427/143250897-4ae8ecbe-227b-410e-8cd1-ee74896524d3.png)

再运行一步，给response赋到值

**Comment by Xm798** [comment]
![image](https://user-images.githubusercontent.com/48074861/143251505-0934be3f-e3e4-4a59-9072-ca8c85262787.png)
39行之后加print，就可以看到response了
![image](https://user-images.githubusercontent.com/48074861/143251629-a5bc19be-e844-459e-a8d2-8b09c19dcfc7.png)

**Comment by 1053960054** [comment]
> 

{'data': None, 'message': 'Please login', 'retcode': 10001}

**Comment by yaomeng0722** [comment]
> > 
> 
> {'data': None, 'message': 'Please login', 'retcode': 10001}

cookie有问题，看看是不是cookie掉了，或者标点啥的错了

**Comment by Xm798** [comment]
> > 
> 
> {'data': None, 'message': 'Please login', 'retcode': 10001}

那就还是 cookies 有问题，按照以下步骤操作：
- 确认米游社 APP 能看到实时便签
- 重新抓取 cookie，并确认配置文件中的 cookie **至少**包含 `ltoken`、`ltuid`、`cookie_token`三项内容， 形如：`"COOKIE": "ltoken=Cxxxxxxxxxxxxxxxxxxx8s; ltuid=1xxxxxxx1; cookie_token=axxxxxxxxxxxxxxxxxxxxxx9",`

**Comment by yaomeng0722** [comment]
![image](https://user-images.githubusercontent.com/45081750/143252610-797f1eac-db44-413f-9661-76e8916f4f55.png)

javascript:(function(){let domain=document.domain;let cookie=document.cookie;prompt('Cookies: '+domain, cookie)})();
像这样加一个书签，进到原神版区后点书签也会直接弹出个窗口来，里面的就可以直接复制用

**Comment by Xm798** [comment]
> > > > 
> > > 
> > > 
> > > {'data': None, 'message': 'Please login', 'retcode': 10001}
> > 
> > cookie有问题，看看是不是cookie掉了，或者标点啥的错了
> 
> 
> 
> > ![image](https://user-images.githubusercontent.com/45081750/143252610-797f1eac-db44-413f-9661-76e8916f4f55.png)
> > 
> > javascript:(function(){let domain=document.domain;let cookie=document.cookie;prompt('Cookies: '+domain, cookie)})(); 像这样加一个书签，进到原神版区后点书签也会直接弹出个窗口来，里面的就可以直接复制用
> 
> 我擦，我重新复制了一遍cookie然后创建容器还是一样报错，但是我把这段cookie放在pycharm就行了，明明是同一段，前面还报错，现在又好了，不知道啥情况

嗯……我这边 docker 是没问题的，你把好了的配置文件直接映射到docker试试呢

**Comment by 1053960054** [comment]
> > > > > 
> > > > 
> > > > 
> > > > {'data': None, 'message': 'Please login', 'retcode': 10001}
> > > 
> > > 
> > > cookie有问题，看看是不是cookie掉了，或者标点啥的错了
> > 
> > 
> > > ![image](https://user-images.githubusercontent.com/45081750/143252610-797f1eac-db44-413f-9661-76e8916f4f55.png)
> > > javascript:(function(){let domain=document.domain;let cookie=document.cookie;prompt('Cookies: '+domain, cookie)})(); 像这样加一个书签，进到原神版区后点书签也会直接弹出个窗口来，里面的就可以直接复制用
> > 
> > 
> > 我擦，我重新复制了一遍cookie然后创建容器还是一样报错，但是我把这段cookie放在pycharm就行了，明明是同一段，前面还报错，现在又好了，不知道啥情况
> 
> 嗯……我这边 docker 是没问题的，你把好了的配置文件直接映射到docker试试呢

我把正常的config.json文件复制到服务器，重新创建容器还是一样报错，但是我直接在服务器git clone然后把config.json文件复制过去，运行index.py却没问题了。

**Comment by 1053960054** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > {'data': None, 'message': 'Please login', 'retcode': 10001}
> > > > 
> > > > 
> > > > cookie有问题，看看是不是cookie掉了，或者标点啥的错了
> > > 
> > > 
> > > > ![image](https://user-images.githubusercontent.com/45081750/143252610-797f1eac-db44-413f-9661-76e8916f4f55.png)
> > > > javascript:(function(){let domain=document.domain;let cookie=document.cookie;prompt('Cookies: '+domain, cookie)})(); 像这样加一个书签，进到原神版区后点书签也会直接弹出个窗口来，里面的就可以直接复制用
> > > 
> > > 
> > > 我擦，我重新复制了一遍cookie然后创建容器还是一样报错，但是我把这段cookie放在pycharm就行了，明明是同一段，前面还报错，现在又好了，不知道啥情况
> > 
> > 
> > 嗯……我这边 docker 是没问题的，你把好了的配置文件直接映射到docker试试呢
> 
> 我把正常的config.json文件复制到服务器，重新创建容器还是一样报错，但是我直接在服务器git clone然后把config.json文件复制过去，运行index.py却没问题了。

我又试了一遍，相同的config.json文件我创建容器后运行报错误，但是直接clone运行index.py却没事

**Comment by yaomeng0722** [comment]
(玄学)

**Comment by Xm798** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > {'data': None, 'message': 'Please login', 'retcode': 10001}
> > > > > 
> > > > > 
> > > > > cookie有问题，看看是不是cookie掉了，或者标点啥的错了
> > > > 
> > > > 
> > > > > ![image](https://user-images.githubusercontent.com/45081750/143252610-797f1eac-db44-413f-9661-76e8916f4f55.png)
> > > > > javascript:(function(){let domain=document.domain;let cookie=document.cookie;prompt('Cookies: '+domain, cookie)})(); 像这样加一个书签，进到原神版区后点书签也会直接弹出个窗口来，里面的就可以直接复制用
> > > > 
> > > > 
> > > > 我擦，我重新复制了一遍cookie然后创建容器还是一样报错，但是我把这段cookie放在pycharm就行了，明明是同一段，前面还报错，现在又好了，不知道啥情况
> > > 
> > > 
> > > 嗯……我这边 docker 是没问题的，你把好了的配置文件直接映射到docker试试呢
> > 
> > 我把正常的config.json文件复制到服务器，重新创建容器还是一样报错，但是我直接在服务器git clone然后把config.json文件复制过去，运行index.py却没问题了。
> 
> 我又试了一遍，相同的config.json文件我创建容器后运行报错误，但是直接clone运行index.py却没事

很奇怪诶……怎么会这样呢……
