### ISSUE TITLE
> > > > {'data': None, 'message': 'Params error', 'retcode': -1}  发生错误，请检查cookie与id是否对应或是否已开启米游社实时便笺功能。

### ISSUE THREAD

**Issue by OtakuNekoP** [yaomeng0722/genshin_task-resin-expedition_alert#35]
> > > > 
> > > 
> > > 
> > > 没有，我在下面加了一行 "print(response)" 都没打印到控制台，不知道这个和java一不一样，我想debug的时候看下里面的值，结果都没有
> > 
> > 
> > 要看的是39行的response，或者在41行之前加 print(response)。 41行的Response.parse_obj是类似数据过滤的东西，估计是不符合要求，所以你打印出来是空值
> 
> ![image](https://user-images.githubusercontent.com/38828427/143250897-4ae8ecbe-227b-410e-8cd1-ee74896524d3.png)

再运行一步，给response赋到值

_Originally posted by @yaomeng0722 in https://github.com/yaomeng0722/genshin_task-resin-expedition_alert/issues/30#issuecomment-977899349_

我到这一步断点出来是  {'data': None, 'message': 'Params error', 'retcode': -1} 
我是欧服账号（UID: 7xxxxxxxx），和这个有关系吗？欧服账号是无法登录 bbs.mihoyo.com的，只能登录 hoyolab.com，cookie也是从hoyolab.com获取的，cookie里面包含ltoken ltuid cookie_token。hoyolab手机app里面可以正常查看实时便签。

**Comment by OtakuNekoP** [comment]
我尝试修改 alert/getinfo/utils.py 添加 os_euro 后得到 {"data":null,"message":"Please login","retcode":10001}

**Comment by OtakuNekoP** [comment]
啊，没事了，找到了一个支持hoyolab的库
https://gitlab.com/y1ndan/genshinhelper2/-/blob/main/genshinhelper/hoyolab.py#L52
总之感谢大佬，打扰了

**Comment by yaomeng0722** [comment]
ヽ(✿ﾟ▽ﾟ)ノ
