### ISSUE TITLE
腾讯云的服务器没救了么？

### ISSUE THREAD

**Issue by xinxinyihao** [yaomeng0722/genshin_task-resin-expedition_alert#37]
腾讯云的服务器没救了么？，难受。

**Comment by yaomeng0722** [comment]
好像是的，之前看到哪里说，在腾讯或者阿里云上的请求会被屏蔽(虽然我也记不清是不是指米游社的api)

**Comment by JDYuuki** [comment]
> 好像是的，之前看到哪里说，在腾讯或者阿里云上的请求会被屏蔽(虽然我也记不清是不是指米游社的api)

 根据隔壁的讨论串（[#522](https://github.com/Arondight/Adachi-BOT/issues/522)），貌似旧版 API 恢复访问了，我回退了俩版本测试通过，~~不过不知道旧版 API 能存活多久~~。
![image](https://user-images.githubusercontent.com/28827378/147635189-65495791-67ee-4eec-a181-96fc1b43f190.png)
![image](https://user-images.githubusercontent.com/28827378/147635175-5d4d9ab9-688f-4418-abb2-6352424d9f3a.png)

**Comment by xinxinyihao** [comment]
> > 好像是的，之前看到哪里说，在腾讯或者阿里云上的请求会被屏蔽(虽然我也记不清是不是指米游社的api)
> 
> 根据隔壁的讨论串（[#522](https://github.com/Arondight/Adachi-BOT/issues/522)），貌似旧版 API 恢复访问了，我回退了俩版本测试通过，~不过不知道旧版 API 能存活多久~。 ![image](https://user-images.githubusercontent.com/28827378/147635189-65495791-67ee-4eec-a181-96fc1b43f190.png) ![image](https://user-images.githubusercontent.com/28827378/147635175-5d4d9ab9-688f-4418-abb2-6352424d9f3a.png)

谢谢谢谢，已改为旧版api，现在运行正常。

**Comment by xinxinyihao** [comment]
> > 好像是的，之前看到哪里说，在腾讯或者阿里云上的请求会被屏蔽(虽然我也记不清是不是指米游社的api)
> 
> 根据隔壁的讨论串（[#522](https://github.com/Arondight/Adachi-BOT/issues/522)），貌似旧版 API 恢复访问了，我回退了俩版本测试通过，~不过不知道旧版 API 能存活多久~。 ![image](https://user-images.githubusercontent.com/28827378/147635189-65495791-67ee-4eec-a181-96fc1b43f190.png) ![image](https://user-images.githubusercontent.com/28827378/147635175-5d4d9ab9-688f-4418-abb2-6352424d9f3a.png)

现在好像又不行了。和以前的问题一样了。

**Comment by yaomeng0722** [comment]
> 现在好像又不行了。和以前的问题一样了。

= =过段时间一定!
